#!/bin/bash

version="0.1.0"
old_ifs="${IFS}"
cache_dir="${HOME}/.cache/mangadl"
dependencies=("ls" "cat" "curl" "wget" "sed" "awk" "tr" "du" "rm" "mkdir" "git" "ouch" "fzf")

# Text colors
red="\033[1;31m"
green="\033[1;32m"
blue="\033[1;34m"
no_color="\033[0m" # Default text color

#########################
# Text output functions #
#########################

print_green() { # Print green text
	printf "${green}%s${no_color}\n" "${*}"
}

print_blue() { # Print blue text
	printf "${blue}%s${no_color}\n" "${*}"
}

print_red() { # Print red text to STDERR
	printf "${red}%s${no_color}\n" "${*}" >&2
}

print_list_item() { # Print text in blue (${1}) and the default color (${2})
	printf "${blue}%s${no_color} ${no_color}%s${no_color}\n" "[${1}]" "${2}"
}

prompt() { 
	# Print text in green (${1}) and blue (${2}) 
	printf "${green}%s${no_color} ${blue}%s${no_color}" "${1}" "${2}"

	# Prompt user and save user input to the variable 'reply'
	read -r reply 
}

show_help() {
	while IFS= read -r line; do
		printf "%s\n" "${line}"
	done <<-EOF
	
	manga-dl ${version} ( github.com/sweetbbak/manga-dl )
	Bash script for reading mangas via the terminal
	Usage:
	  manga-dl [Options]
	Options:
	  -h, --help		Print this help page
	  -V, --version		Print version number
	  -u, --update		Fetch latest version from the Github repository
	  -f, --fullscreen	Open Zathura in fullscreen mode 
	  -l, --last-session	Open last session
	  -c, --cache-size	Print cache size (${cache_dir})
	  -C, --clear-cache	Clear cache (${cache_dir})
	EOF
}

show_version() {
	print_green "Version: ${version}"
}

check_number_input() {
	min_num="${1}"
	max_num="${2}"
	input_num="${3}"

	if 	[[ ${input_num} -ge ${min_num} ]] &&
		[[ ${input_num} -le ${max_num} ]]	
	then
		return 1
	else
		print_red "Invalid selection"
		printf "\n"
		return 0
	fi
}

reset_ifs() {
	IFS="${old_ifs}"
}

###################
# Cache functions #
###################

show_cache_size() {
	# If cache_dir does not exist, create it
	if [[ ! -d "${cache_dir}" ]]; then
		mkdir --parents "${cache_dir}"
	fi

	cache_size="$(du -sh "${cache_dir}" | awk '{print $1}')"

	print_green "Cache size: ${cache_size} (${cache_dir})"
}

clear_cache() {
	show_cache_size

	prompt "Proceed with clearing the cache?" "[Y/N]: "

	# Convert user input to lowercase
	user_input="$(printf "%s" "${reply}" | tr "[:upper:]" "[:lower:]")"

	if [[ "${user_input}" == "y" ]]; then
		rm -r "${cache_dir:?}/"
		print_green "Cache successfully cleared"
	fi
}

cache_session() {
	# Save variables in session file
	printf '%s\n' \
		"${mod_manga_title}" "${selected_chapter_num}" "${manga_url}" "${chapter_urls[*]}" > \
		"${cache_dir}/session"
}

read_last_session() {
	if [[ ! -f "${cache_dir}/session" ]]; then
		print_red "ERROR: Session file not found"
	else
		session=($(cat "${cache_dir}/session"))
		
		mod_manga_title="${session[0]}"
		unset "session[0]"

		selected_chapter_num="${session[1]}"
		unset "session[1]"

		manga_url="${session[2]}"
		unset "session[2]"

		# Replace underscores with spaces
		manga_title="$(printf "%s" "${mod_manga_title}" | tr "_" " ")" 
		chapter_urls=("${session[@]}")
		chapter_count=${#chapter_urls[@]}
		chapter_url="${chapter_urls[${selected_chapter_num} - 1]}"

		# Update chapter list in the background 
		scrape_chapter_list &
	fi
}

