#!/bin/bash

version="0.1.0"
old_ifs="${IFS}"
cache_dir="${HOME}/.cache/mangadl"
dependencies=("ls" "cat" "curl" "wget" "sed" "awk" "tr" "du" "rm" "mkdir" "git" "ouch" "fzf")

# Text colors
red="\033[1;31m"
green="\033[1;32m"
blue="\033[1;34m"
no_color="\033[0m" # Default text color