#!/bin/bash

version="0.1.0"
old_ifs="${IFS}"
cache_dir="${HOME}/.cache/mangadl"
dependencies=("ls" "cat" "curl" "wget" "sed" "awk" "tr" "du" "rm" "mkdir" "git" "ouch" "fzf")

# Text colors
red="\033[1;31m"
green="\033[1;32m"
blue="\033[1;34m"
no_color="\033[0m" # Default text color

#########################
# Text output functions #
#########################

print_green() { # Print green text
	printf "${green}%s${no_color}\n" "${*}"
}

print_blue() { # Print blue text
	printf "${blue}%s${no_color}\n" "${*}"
}

print_red() { # Print red text to STDERR
	printf "${red}%s${no_color}\n" "${*}" >&2
}

print_list_item() { # Print text in blue (${1}) and the default color (${2})
	printf "${blue}%s${no_color} ${no_color}%s${no_color}\n" "[${1}]" "${2}"
}

prompt() { 
	# Print text in green (${1}) and blue (${2}) 
	printf "${green}%s${no_color} ${blue}%s${no_color}" "${1}" "${2}"

	# Prompt user and save user input to the variable 'reply'
	read -r reply 
}

show_help() {
	while IFS= read -r line; do
		printf "%s\n" "${line}"
	done <<-EOF
	
	manga-dl ${version} ( github.com/sweetbbak/manga-dl )
	Bash script for reading mangas via the terminal
	Usage:
	  manga-dl [Options]
	Options:
	  -h, --help		Print this help page
	  -V, --version		Print version number
	  -u, --update		Fetch latest version from the Github repository
	  -f, --fullscreen	Open Zathura in fullscreen mode 
	  -l, --last-session	Open last session
	  -c, --cache-size	Print cache size (${cache_dir})
	  -C, --clear-cache	Clear cache (${cache_dir})
	EOF
}

show_version() {
	print_green "Version: ${version}"
}