[services]
lutris = True
gog = True
egs = True
origin = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 12
show_hidden_games = false
show_advanced_options = True
width = 1886
height = 958
window_x = 1933
window_y = 13
maximized = False
selected_category = runner:wine

