# sourcing external config files
source=~/.config/hypr/configs/exec.conf
source=~/.config/hypr/configs/window_rules.conf
source=~/.config/hypr/configs/keybinds.conf
source=~/.config/hypr/configs/monitors.conf
source=~/.config/hypr/configs/env.conf

$BROWSER = firefox

input {
	kb_layout    = us
	repeat_delay = 290
	repeat_rate  = 70
}

general {
    gaps_in 		    = 5
    gaps_out 		    = 10
    border_size 	    = 3
    sensitivity         = 1.00
    apply_sens_to_raw   = 0
    col.active_border   = rgba(008787FF) rgba(5F5FFFFF) rgba(F783D0FF) 90deg
    col.inactive_border = rgba(00000000)
    resize_on_border    = true
}

decoration {
    blur {        
        enabled           = true
        size              = 10
        passes            = 5
        new_optimizations = true
        xray              = true
        # blurls          = gtk-layer-shell
        # blurls          = waybar
    }

    rounding              = 8
}

dwindle {
    no_gaps_when_only      = false
    pseudotile             = true
    force_split            = 2
    preserve_split         = true
}

misc {
    # enable_swallow	        = true
    # swallow_regex	        = ^(org.wezfurlong.wezterm:foot)$
    # swallow_regex	        = ^(kitty)$
    # swallow_exception_regex = ^(.*swayimg.*)$
    # swallow_exception_regex = ^(.*wev.*)$
    # swallow_exception_regex = ^(.*floatimg.*)$
    force_hypr_chan         = true
}

animations {
    bezier=pace,0.46, 1, 0.29, 0.99
    bezier=overshot,0.13,0.99,0.29,1.1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    animation=windowsIn,1,6,md3_decel,slide
    animation=windowsOut,1,6,md3_decel,slide
    animation=windowsMove,1,6,md3_decel,slide
    animation=fade,1,10,md3_decel
    animation=workspaces,1,7,md3_decel,slide
    animation=specialWorkspace,1,8,md3_decel,slide
    animation=border,1,10,md3_decel
}
