local welcome_own_commands=(
    # Legend: --field=" name!icon!description":fbtn "command"

    --field=" A Kernel Manager!system-software-install!Simple kernel manager and info source":fbtn  "akm"
    --field=" Mousepad!accessories-text-editor!Mousepad text editor":fbtn                           "mousepad"
    --field=" Firefox web browser!firefox-default!Browse the web with Firefox":fbtn                 "firefox"
)

local activate_own_commands_tab=yes
local columns_for_own_commands=2
local show_predefined_buttons_at_own_commands=no

personal_commands_init yes "" no

personal_commands_add "neovide" \
                      "GUI Neovim" \
                      "Text editor" \
                      "Simple text editor"

personal_commands_add "firefox" \
                      "Firefox web browser" \
                      "firefox-default" \
                      "Browse the web with Firefox"

personal_commands_add "kitty -e" \
                      "Xed" \
                      "accessories-text-editor" \
                      "Xed text editor with new window" \
                      "xed"