#!/bin/sh

autostart="nm-applet"
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Applets :
#nm-applet &
#blueman-applet &
#volumeicon &
#xfce4-power-manager &

# Arandr
sh ~/.screenlayout/arandr-layout.sh &

# Picom
picom

# Polkit :
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Keybord auto-repeat :
xset r rate 300 50 &

# Clipordmanager :
clipmenud &

# Wallpaper :
nitrogen --restore &

# conky
#conky -c ~/.config/conky/otis-forest.conkyrc\ &

# Sevices info :
#echo "false" > /tmp/blue_light_state

# Compositor  :
#autostart="picom"
#for program in $autostart; do
#	pidof -s "$program" || setsid -f "$program"
#done >/dev/null 2>&1

# Updates :
#notify-send -t 8000 "You have $(checkupdates | wc -l) update 📦" &

