theme = "rose_pine_moon"

# General Helix's configuration
[editor]
line-number = "relative"
cursorline = true
color-modes = true

# File explorer configuration
[editor.file-picker]
hidden = false
parents = false

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

# Helix's statusline
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["selections", "position"]
separator = "│"
mode.normal = "NORMAL  "
mode.insert = "INSERT  "
mode.select = "SELECT 麗"

[keys.normal]
"C-r" = [":config-reload"]
"C-s" = [":w"]
"C-o" = [":open ~/.config/helix/config.toml"]
"C-O" = [":open ~/.snippets"]
"g" = { a = "code_action" }
"G" = ["goto_last_line"]
"Z" = { Q = ":quit!" ,  Z = ":write-quit!" }
"D" = ["extend_to_line_bounds", "delete_selection"]
"0" = ["goto_line_start"]
"$" = ["goto_line_end"]
"=" = [ ":format" ]

# test for project launcher
[keys.normal.space]
c = ":sh kitty @ send-text --match 'title:^Terminal' cargo run \\\\n" 
t = ":sh kitty @ send-text --match 'title:^Terminal' 'clear \\ncargo test \\n'"

# recent additions
"^" = "goto_first_nonwhitespace"
V = ["select_mode", "extend_to_line_bounds"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable


# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

[keys.select]
"D" = ["extend_to_line_bounds", "delete_selection"]

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
